name: Deploy httpbhib app to Amazon EKS with Helm and Kustomize

on:
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: eu-west-1                 
  ECR_REPOSITORY: public.ecr.aws/#####
  CLUSTER_NAME: aweomse-stuff

jobs:
  deploy:
    name: Deploy httpbin
    runs-on: ubuntu-latest

    steps:
    - name: Split branch name
      env:
        BRANCH: ${{ github.ref_name }}
      id: split
      run: echo "::set-output name=branch_name::${BRANCH##*/}"
    
    - uses: actions/checkout@v4
      with:
        repository: postmanlabs/httpbin
        path: httpbin
    
    - name: Build and push to dockergub
      uses: docker/build-push-action@v5
      with:
        push: true
        file: ./httpbin/Dockerfile
        tags: ${{ steps.split.outputs.branch_name }} 

#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ${{ env.AWS_REGION }}

#    - name: Login to Amazon ECR
#      id: login-ecr
#      uses: aws-actions/amazon-ecr-login@v1
#      with:
#          registry-type: public

