name: Deploy Get Schwifty app to GKE with Helm and Kustomize

on:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy Get Schwifty App
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout current repository
      with:
        path: k8s-preview-envs   
    
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Build, tag, and push image to Dockerhub
       id: build-image
       env:
         REPO_NAME: "dorsav/myapp"
         IMAGE_TAG: ${{ github.head_ref }}
       run: |
         # Builds a docker image and pushes it to Dockerhub
         docker build -t $REPO_NAME:$IMAGE_TAG -f ./k8s-preview-envs/Dockerfile ./k8s-preview-envs
         docker push $REPO_NAME:$IMAGE_TAG
         echo "::set-output name=image::$REPO_NAME:$IMAGE_TAG" 

    - id: 'auth'
      name: Login to GCP
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Deploy to designated preview namespace
      working-directory: k8s-preview-envs/kustomize/overlays
      run: |
        kubectl create namespace ${{ github.head_ref }} || true 
        mkdir ${{ github.head_ref }} && cd ${{ github.head_ref }}
        kustomize create --resources ../../../helm/myapp/
        kustomize edit set image dorsav/myapp:${{ github.head_ref }}
        kubectl apply -k . -n ${{ github.head_ref }}
